### ISSUE TITLE
ImportError: 'speechbrain' must be installed

### ISSUE THREAD

**Issue by suminhthanh** [victor-upmeet/whisperx-replicate#2]
```
ImportError: 'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings. Visit https://speechbrain.github.io for installation instructions.
{"error": "'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings. Visit https://speechbrain.github.io for installation instructions.", "prediction_id": null, "logger": "cog.server.runner", "timestamp": "2024-03-11T14:37:43.175819Z", "severity": "INFO", "message": "prediction failed"}
```

when use diarization it happens

**Comment by markmurrayjw** [comment]
I've been running a slightly older version of the whisperx-replicate and hit this issue on Friday. I tested the latest version and the older version and both had the same 'speechbrain' problem. Our solution was to create our own deployment in replicate and have it set to a cold start (to keep costs down) and this is working fine for us.
Appreciate this is not a bug fix but at least its a workaround until this issue can get resolved. Just a suggestion, perhaps the end-point just needs re-released again to refresh it? Not sure if that's even possible to do to on replicate.

**Comment by rdewolff** [comment]
I have the same issue.

Any workaround?

**Comment by markmurrayjw** [comment]
Yeah as I said in my previous post. Create your own deployment and use that - it worked for me so defo worth a try.

**Comment by sonicbaume** [comment]
@victor-upmeet Diarization is still broken. Are you able to re-release the model as suggested above, to see if that resolves the issue? 🙏

**Comment by lukaesch** [comment]
> I've been running a slightly older version of the whisperx-replicate and hit this issue on Friday. I tested the latest version and the older version and both had the same 'speechbrain' problem. Our solution was to create our own deployment in replicate and have it set to a cold start (to keep costs down) and this is working fine for us. Appreciate this is not a bug fix but at least its a workaround until this issue can get resolved. Just a suggestion, perhaps the end-point just needs re-released again to refresh it? Not sure if that's even possible to do to on replicate.

I created an own deployment on Replicate of victor-upmeet/whisperx:82680112 and it still shows the same error.

Did you configure something else?

**Comment by sonicbaume** [comment]
I forked it and made some minor modifications to make it work, which I've submitted as pull requests. See https://github.com/sonicbaume/whisperx-replicate and https://replicate.com/sonicbaume/whisperx

**Comment by victor-upmeet** [comment]
Hi there

Problem has been solved, new version has been pushed on Replicate: 84d2ad2d6194fe98a17d2b60bef1c7f910c46b2f6fd38996ca457afd9c8abfcb
