### ISSUE TITLE
Diarization breaks at replicate. Not diarizing, works.

### ISSUE THREAD

**Issue by xmontero** [victor-upmeet/whisperx-replicate#7]
Hi! I'm using replicate to try out the diarization.

I'm using a file of 1'15" to test. It's an mp3 converted from an AMR file from a phone voice call recording.

When running without language (to force detection), all the default parameters, and alignment and diarization set to false, it works.

The file is in catalan ("ca") and it properly detects it.

When running it setting alignment + diarization to true, it breaks. I get this output:

Logs:

No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu121. Bad things might happen unless you revert torch to 1.x.
Detected language: ca (0.92) in first 30s of audio...
Could not download 'pyannote/speaker-diarization-3.1' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:
>>> Pipeline.from_pretrained('pyannote/speaker-diarization-3.1',
...                          use_auth_token=YOUR_AUTH_TOKEN)
If this still does not work, it might be because the pipeline is gated:
visit https://hf.co/pyannote/speaker-diarization-3.1 to accept the user conditions.
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cog/server/worker.py", line 354, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 167, in predict
result = diarize(audio, result, debug, huggingface_access_token, min_speakers, max_speakers)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 291, in diarize
diarize_model = whisperx.DiarizationPipeline(use_auth_token=huggingface_access_token, device=device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/whisperx/diarize.py", line 19, in __init__
self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to'

It breaks both in victor-upmeet/whisperx and victor-upmeet/whisperx-a40-large

What do I have to do to use diarization?

**Comment by victor-upmeet** [comment]
You need to specify a hugging face access token in the parameters of the prediction. The hugging face account the access token is attached to must have access to https://huggingface.co/pyannote/segmentation-3.0 and https://huggingface.co/pyannote/speaker-diarization-3.1

**Comment by xmontero** [comment]
Thanks victor. Tested. It works.

I never "accepted a model" before neither I created a HuggingFace token to access models, so I had a bit of trouble to decode what you were saying. Specially in the grained permission window, which has a lot of options and I didn't know what ones I had to grant permissions for.

Allow me, please, for the huggingface newbies like me that end up here, to clarify the answer:

🟦 Replicate will make an API call to huggingface to use the diarization and aligning the output.

🟦 Therefore you need to setup a token in HuggingFace.

🟦 There are 2 steps to take:

🟦🟩 Step 1) Enter into each of the 2 models needed and "accept the terms". To do so, you'll need to set your company name as well as the website of your company. Visit https://huggingface.co/pyannote/segmentation-3.0 and https://huggingface.co/pyannote/speaker-diarization-3.1 and below the title you'll find a huge acceptance box.
![image](https://github.com/user-attachments/assets/467feb0e-72d7-4aa5-b8c7-29a107f2de9a)

🟦🟩 Step 2) Then in profile | settings dropdown menu | access tokens in the left menu | create new token button, you'll be presented a permission screen. Use te `fine-grained` mode so you reduce all the attack-surface and then set a name for your token. I generally use a different token for each client of any API so I called this one: `replicate-whisperx-diarization`
![image](https://github.com/user-attachments/assets/38976348-f7cf-4b2e-9d6a-e8bd7051c5b8)

🟦🟩 Step 2 - cont.) Then add the 2 repositories here by the repo name. The autocompletion only works on full-names so it'll not appear at mid-typing. Accept the proposed model in the dropdown:
![image](https://github.com/user-attachments/assets/3eceaf63-e7b5-4f0c-8b60-5468e7a0bc73)

🟦🟩 Step 2 - cont.) Do this with the 2 repos. At the end a "read permission" is already granted:
![image](https://github.com/user-attachments/assets/f15f0c7c-d4d9-48f8-8922-b5d897256127)

🟦🟩 Step 2 - cont.) No other permissions are needed. Leave all the other blank. Save the token, copy it and save it in a safe place. Then use it inside the token box in the replicate playground, just after the diarization checkboxes:
![image](https://github.com/user-attachments/assets/f257148a-e05f-40f9-a1a4-4d48edbed6a4)

**Comment by bbauman1** [comment]
thank you @xmontero that was very helpful. did you figure out if this means added cost from huggingface when calling this api using diarization?  if so did you subscribe to their $9/month tier and pay per usage?

**Comment by xmontero** [comment]
@bbauman1 

Hi, Brett! No, I am not using huggingface at $9/mo. I am currently transcribing **without** diarization, locally in my laptop with this:

    docker run \
        --rm \
        --memory=8g \
        --cpus=3 \
        --gpus all \
        --user $(id -u):$(id -g) \
        -v ${PWD}:/app \
        -v /files/whisperx-language-models-cache:/.cache \
        ghcr.io/jim60105/whisperx:latest \
            -- \
            ${LANGUAGE_DOCKER_SWITCH} \
            --model medium \
            --output_format srt \
            "$MP3_FILE"

When diarization works I'll re-transcribe some thousands of calls.

I am still very interested in having diarization.

I can't recall if diarization worked properly in the last tests!!

How can I help?

**Comment by bbauman1** [comment]
I think it is working but trying to understand the hugging face dependency and costs. I might just switch to a non-replicate transcription provider

**Comment by bbauman1** [comment]
@xmontero can you comment on if there are additional costs from hugging face or is replicate just "reading" from hugging face in a way that doesn't incur charges? when using diarization

**Comment by bbauman1** [comment]
update - you are not charged by hf
